#!/usr/bin/env python3
"""
split.py：TEAM.md拆分工具（按角色拆分为独立文件）
用法：python3 split.py
关键约束：从冻结源 TEAM.md.bak-pre-split 按 MAP 重新生成 docs/ 与 TEAM.md 索引；sha256 逐段校验；冻结源缺失时 exit 2
"""
import hashlib
import io
import json
import os
import sys

# 冻结源：拆分前的完整 TEAM.md 备份。仓库不附带该文件，
# 缺失时本脚本只做提示后退出，不会改动 docs/ 与 TEAM.md。
BAK = 'TEAM.md.bak-pre-split'
if not os.path.exists(BAK):
    print('split.py: 未找到冻结源 %s（仓库不附带），跳过拆分。' % BAK, file=sys.stderr)
    sys.exit(2)
SRC = BAK
IDX_OUT = 'TEAM.md'   # index output; MUST != SRC (writing to SRC destroys the source)
assert IDX_OUT != SRC, 'IDX_OUT == SRC would overwrite the frozen source'
lines = io.open(SRC, encoding='utf-8').read().split('\n')
N = len(lines)
assert N > 1000, 'unexpected line count %d' % N

# (start, end, target)  -- 1-based, inclusive. IDX = regenerate as index.
MAP = [
    (1, 1, 'IDX'),
    (2, 8, 'IDX'),
    (9, 65, 'docs/00-architecture/overview.md'),
    (66, 67, 'IDX'),
    (68, 107, 'IDX'),
    (108, 145, 'IDX'),
    (146, 191, 'IDX'),
    (192, 237, 'IDX'),
    (238, 272, 'IDX'),
    (273, 333, 'IDX'),
    (334, 418, 'IDX'),
    (419, 437, 'IDX'),
    (438, 459, 'IDX'),
    (460, 482, 'docs/00-architecture/contracts.md'),
    (483, 511, 'docs/00-architecture/org.md'),
    (512, 533, 'docs/00-architecture/contracts.md'),
    (534, 556, 'docs/00-architecture/org.md'),
    (557, 582, 'docs/00-architecture/quickstart.md'),
    (583, 590, 'docs/00-architecture/quickstart.md'),
    (591, 600, 'docs/00-architecture/quickstart.md'),
    (601, 737, 'CHANGELOG.md'),
    (738, 752, 'docs/00-architecture/files.md'),
    (753, 757, 'IDX'),
    (758, 778, 'docs/tools/tools-writing.md'),
    (779, 794, 'docs/tools/tools-design.md'),
    (795, 826, 'docs/tools/tools-media.md'),
    (827, 867, 'docs/tools/tools-release.md'),
    (868, 875, 'docs/00-architecture/contracts.md'),
    (876, 893, 'docs/tools/tools-design.md'),
    (894, 949, 'CHANGELOG.md'),
    (950, 974, 'docs/00-architecture/training.md'),
    (975, 997, 'CHANGELOG.md'),
    (998, N, 'CHANGELOG.md'),
]

# --- coverage: no overlap, no gap -------------------------------------------
seen = [False] * (N + 2)
for a, b, t in MAP:
    assert 1 <= a <= b <= N, 'range %d-%d out of bounds (N=%d)' % (a, b, N)
    for i in range(a, b + 1):
        assert not seen[i], 'overlap at line %d' % i
        seen[i] = True
missing = [i for i in range(1, N + 1) if not seen[i]]
assert not missing, 'missing lines: %s' % missing[:20]

buckets = {}
src_hashes = {}
for a, b, t in MAP:
    seg = '\n'.join(lines[a - 1:b])
    h = hashlib.sha256(seg.encode('utf-8')).hexdigest()
    buckets.setdefault(t, []).append((a, b, seg, h))
    src_hashes['%d-%d' % (a, b)] = h

for d in ('docs/00-architecture', 'docs/roles', 'docs/tools'):
    os.makedirs(d, exist_ok=True)

WALL = 2048
manifest = []
over = []

for path, parts in buckets.items():
    if path == 'IDX':
        continue
    txt_parts = [p[2] for p in parts]
    txt = '\n\n'.join(txt_parts) + '\n'
    tok = len(txt)
    first = ''
    for ln in txt.split('\n'):
        if ln.startswith('#'):
            first = ln.lstrip('#').strip()
            break
    sid = os.path.basename(path)[:-3]
    fm = ('---\nid: %s\ntitle: "%s"\ntokens: %d\nsource: "%s"\n'
          'source_lines: "%s"\n---\n\n'
          % (sid, first.replace('"', "'"), tok, SRC,
             ','.join('%d-%d' % (p[0], p[1]) for p in parts)))
    io.open(path, 'w', encoding='utf-8').write(fm + txt)
    manifest.append({'id': sid, 'path': path, 'tokens': tok,
                     'over': tok > WALL,
                     'source_lines': [p[1] for p in parts]})
    if tok > WALL:
        over.append((path, tok))

# --- index: title + companion-file list + generated nav ---------------------
idx_segs = [p[2] for p in buckets['IDX'] if p[2].strip()]
idx_body = ('\n\n'.join(idx_segs)).strip('\n') + '\n'

rows = []
for m in sorted(manifest, key=lambda x: x['path']):
    layer = 'architecture' if '/00-architecture/' in m['path'] else (
        'roles' if '/roles/' in m['path'] else (
            'tools' if '/tools/' in m['path'] else 'archive'))
    rows.append('| %s | [%s](%s) | %d | %s |' % (
        layer, m['id'], m['path'], m['tokens'],
        'OVER' if m['over'] else 'ok'))
# fix header columns (6 cols: layer/id/file/tokens/wall = 5)
nav = ('\n## Index (auto-generated by split.py -- do not edit)\n\n'
       '| layer | id | file | tokens | wall |\n|---|---|---|---|---|\n%s\n'
       % '\n'.join(rows))

index_txt = idx_body + '\n' + nav
io.open(IDX_OUT, 'w', encoding='utf-8').write(index_txt)
index_tok = len(index_txt)
manifest.append({'id': 'TEAM', 'path': IDX_OUT, 'tokens': index_tok,
                 'over': index_tok > WALL, 'source_lines': [1]})
if index_tok > WALL:
    over.append((SRC, index_tok))

io.open('docs/manifest.json', 'w', encoding='utf-8').write(
    json.dumps({'wall': WALL, 'source_lines': N, 'files': manifest},
               ensure_ascii=False, indent=1))

# --- verify: re-read every output, recompute hashes of source segments -----
errors = []
for a, b, t in MAP:
    if t == 'IDX':
        continue
    seg = '\n'.join(lines[a - 1:b])
    raw = io.open(t, encoding='utf-8').read()
    body = raw.split('---\n\n', 1)[1]
    body_norm = body.strip('\n')
    # parts joined with blank line, so compare per-segment instead
    written = body_norm
    if seg.strip() not in written:
        errors.append('segment %d-%d not found verbatim in %s' % (a, b, t))

print('source lines      :', N)
print('map entries       :', len(MAP))
print('files written     :', len(manifest))
print('index tokens      :', index_tok)
print('over wall (>2048) :', len(over))
for p, t in over:
    print('   OVER', p, t)
print('verbatim errors   :', len(errors))
for e in errors[:10]:
    print('   ', e)
assert not errors, 'content mismatch -- abort'
print('RESULT: zero content change, all segments verbatim')
# END_OF_SPLIT_SCRIPT
